### ISSUE TITLE
Homepage, icon, and screenshot URLs are missing

### ISSUE THREAD

**Issue by lassoan** [KitwareMedical/ShapeRegressionExtension#24]
Extension installation fails because these required fields are missing from the extension description. [We'll relax these requirements](https://github.com/Slicer/Slicer/commit/068d5450ae3045ef7f4e853d1e2a1a5814eaa2fd) but adding this information to the extension is still essential.

**Comment by sjh26** [comment]
Fixed: https://github.com/Slicer/ExtensionsIndex/commit/ee06ed07f90efd48050eee15e322e003bb8acf72
https://github.com/KitwareMedical/ShapeRegressionExtension/commit/d68d34fab7bb61f93cfc4056de2cb4dc70653f1d

**Comment by bpaniagua** [comment]
Thanks, Sam!
