### ISSUE TITLE
Cmake error during building

### ISSUE THREAD

**Issue by jamesfishbaugh** [KitwareMedical/ShapeRegressionExtension#3]
I encounter the following error, for various versions of cmake:

```
...
-- SuperBuild - First pass
-- SuperBuild - First pass - done
-- SuperBuild - shape4D => Requires FFTW, 
-- SuperBuild -   FFTW[OK]
-- SuperBuild - shape4D[OK]
CMake Error at SuperBuild.cmake:85 (ExternalProject_AlwaysConfigure):
  Unknown CMake command "ExternalProject_AlwaysConfigure".
Call Stack (most recent call first):
  CMakeLists.txt:69 (include)
```

I didn't change anything during configuration, I left everything on default settings.  

@phcerdan @jcfr

**Comment by phcerdan** [comment]
That command is provided by [Artichoke](https://cmake-artichoke.readthedocs.io/en/latest/genindex.html), @jcfr might provide more information, are you using a modern Slicer? I am configuring/building it right now with no problems.

**Comment by jamesfishbaugh** [comment]
I am using Slicer version 4.7.0. Can I point to a build of SlicerSALT instead?

**Comment by jcfr** [comment]
Latest version of the extension are expected to work with the latest version of Slicer.

> Can I point to a build of SlicerSALT instead?

Assuming you have SlicerSALT built in `/path/to/SlicerSALT-build`, you can build the extension passing `-DSlicer_DIR:PATH=/path/to/SlicerSALT-build/Slicer-build`

This also work with a regular build of Slicer passing `-DSlicer_DIR:PATH=/path/to/Slicer-build/Slicer-build`

**Comment by jcfr** [comment]
Slicer  4.7.0 is also quite old, I definitively recommend to upgrade your local build tree. Let us know if you have any issue doing so.
