### ISSUE TITLE
RegressionVisualization 3D rendering issue

### ISSUE THREAD

**Issue by jamesfishbaugh** [KitwareMedical/ShapeRegressionExtension#5]
When viewing a surface in the 3D scene view at certain angles the shape will be not be rendered properly. Instead, there is a strange transparency and portions of the shape that should be occluded are shown through the surface. I attach a sequence of images to illustrate the issue (3rd image).

![shape1](https://user-images.githubusercontent.com/12160522/44751406-18cba780-aae6-11e8-883b-80785be0c542.png)
![shape2](https://user-images.githubusercontent.com/12160522/44751411-1c5f2e80-aae6-11e8-9ade-5223a91e924b.png)
![shape3](https://user-images.githubusercontent.com/12160522/44751415-1d905b80-aae6-11e8-9747-cd0c141f081d.png)
![shape4](https://user-images.githubusercontent.com/12160522/44751417-1f5a1f00-aae6-11e8-9eaa-69bff13af4e3.png)

**Comment by bpaniagua** [comment]
Thanks @jamesfishbaugh I think this is the surface normals
@phcerdan could you please have a look on how the surfaces are loaded into the scene and into the sequence data object and make sure a vtkSurfaceNormals filter is used with the "autoorient" option to true?

**Comment by phcerdan** [comment]
@bpaniagua sure, but I am missing a little bit of context here (I have never used this module).
@jamesfishbaugh may I get a reproducible step by step to the error? 
If that step-by-step does not include the generation of that surface file, could you please upload it here?
Thanks!

**Comment by jamesfishbaugh** [comment]
@bpaniagua, @phcerdan the step-by-step instructions to generate the surface file require running RegressionComputation with specific input shapes and parameter settings. Instead, I upload the estimated sequence ([sequence.zip](https://github.com/KitwareMedical/ShapeRegressionExtension/files/2333667/sequence.zip)). I hope this is sufficient.

**Comment by phcerdan** [comment]
Thanks, @jamesfishbaugh, I can see the problem you mention with that sequence file, but I cannot reproduce the problem from RegressionVisualization. Could you share a folder that can work as an input to the module?

![slicersalt_regseg](https://user-images.githubusercontent.com/3021667/44816421-3ebd7e80-abb0-11e8-9cd5-ebcba0850db2.png)

**Comment by jamesfishbaugh** [comment]
@phcerdan you can extract the sequence.zip file into a folder, select that folder as the "Input Directory", and then put "Regression_output_final_time_" in as the Rootname (without quotes). That should load the sequence.

Also, I have pushed some changes recently to the repository. I didn't change anything related to sequences, but if you are unable to reproduce the problem, you might consider building the current version.

**Comment by phcerdan** [comment]
I tried that but I was getting errors, I'll use your latest version, thanks!

**Comment by phcerdan** [comment]
IO not working, opening #7.

**Comment by phcerdan** [comment]
This function fixes the models, taken from [SurfaceToolbox](https://github.com/Slicer/Slicer/blob/master/Modules/Scripted/SurfaceToolbox/SurfaceToolbox.py#L458-L466), and thanks @bpaniagua for pointing it out.

```python
  def autoOrientNormals(self, model):
    surface = None
    surface = model.GetPolyDataConnection()
    normals = vtk.vtkPolyDataNormals()
    normals.SetAutoOrientNormals(True)
    normals.SetFlipNormals(False)
    normals.SetSplitting(False)
    normals.ConsistencyOn()
    normals.SetInputConnection(surface)
    surface = normals.GetOutputPort()
    model.SetPolyDataConnection(surface)
    return model
```
![peek 2018-08-30 11-26](https://user-images.githubusercontent.com/3021667/44862087-f782cc80-ac47-11e8-97f0-10c8496b3423.gif)

I guess fixing the normals should be done at the data level, this is not a rendering problem. @jamesfishbaugh should we fix the normals in the RegressionComputation module?

**Comment by jamesfishbaugh** [comment]
@phcerdan this is a good point, it should done in as part of RegressionComputation. 

As long as there is not a large performance cost, I think it should be included in RegressionVisualization as well, to deal with "legacy" models. If I want to visualize and old model, it isn't convenient to re-estimate from scratch or fix the normals with a script or outside application. I will experiment to see if it will have an impact on performance.

**Comment by phcerdan** [comment]
Ok, I will open a PR to add it in the visualization as well.
